Cleanup: Fix missing operator++() for enum type
Error was:

  datetime.c:1063:9: error: no match for 'operator++' (operand type is 'NPY_DATETIMEUNIT')
    1063 |         ++unit;
         |         ^~~~~~