[temp] Fix libm not detected due to missing "log" symbol
Error was:

  Traceback (most recent call last):
    File "setup.py", line 448, in check_mathlib
      raise RuntimeError(
    RuntimeError: math library missing; rerun setup.py after setting the MATHLIB env variable